[package]
name = "lpm"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30"  # Latest compatible version
tui = "0.19"
crossterm = "0.27"
gtk = "0.18"
plotters = "0.3"
tokio = { version = "1", features = ["full"] }
glib = "0.18"
lazy_static = "1.4.0"
